import type { Metadata } from "next";
import { League_Spartan } from "next/font/google";
import "./globals.css";
import {TanstackProvider} from "@/providers";
import { ToastProvider } from "@/components/core/Toast/ToastProvider";

const leagueSpartan = League_Spartan({
  variable: "--font-league-spartan",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Kurth Glass",
  description: "Generated by create next app",
  icons: {
    icon: [{ url: "/logo.png", type: "image/png" }],
    shortcut: [{ url: "/logo.png", type: "image/png" }],
    apple: [{ url: "/logo.png", type: "image/png" }],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${leagueSpartan.variable} ${leagueSpartan.className} antialiased`}
      >
        <TanstackProvider>
          <ToastProvider>{children}</ToastProvider>
        </TanstackProvider>
      </body>
    </html>
  );
}
